spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: daejong
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  port: 8080
  context-path: /sell

# 第一种配置日志方式--简单
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  level: debug
#  file: /Users/daejong/Desktop/sell.log

# 第二种方式 即使使用灵活的xml配置文件. logback-spring.xml

